---
- name: "Delete VPC"
  tags:
     - delete
  local_action:
       module: ec2_vpc
       state: absent
       vpc_id: '{{ id }}'
       region: us-east-1
       resource_tags: "{}"
       wait: yes