---
# This playbook deploys the whole application stack in this site.

- name: create VPC
  hosts: localhost
  tags:
     - create

  roles:
    - createvpc

- name: delete VPC
  hosts: localhost
  tags:
     - delete

  roles:
    - deletevpc