---
- name: "Provision VPC"
  tags:
     - create
  local_action:
       module: ec2_vpc
       state: present
       cidr_block: "{{ cidr_block }}"
       resource_tags: { "Name":"VPCFromAnsible", "Environment":"Development" }
       subnets:
          - cidr: "{{ cidr_sn1 }}"
            az: "{{ az1 }}"
            resource_tags: { "Name":"VFA_PubSN_	1", "Environment":"Dev", "Tier" : "Web" }
          - cidr: "{{ cidr_sn2 }}"
            az: "{{ az2 }}"
            resource_tags: { "Name":"VFA_PubSN_	2", "Environment":"Dev", "Tier" : "App" }
          - cidr: "{{ cidr_sn3 }}"
            az: "{{ az1 }}"
            resource_tags: { "Name":"VFA_PvtSN_	1", "Environment":"Dev", "Tier" : "DB" }
       internet_gateway: True
       route_tables:
          - subnets:
              - "{{ cidr_sn1 }}"
              - "{{ cidr_sn2}} "
            routes:
              - dest: 0.0.0.0/0
                gw: igw
          - subnets:
              - "{{ cidr_sn3 }}"
            routes:
              - dest: 0.0.0.0/0
                gw: igw
       region: "{{ aws_region }}"
  register: vpc